version: '3.8'

services:
  
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always    
    command: redis-server
    platform: linux/amd64
    volumes:
      - redis-data:/data
    networks:
      - my_network

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: yourdir_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my_network  

  frontend:
    container_name: frontend
    build:
      context: ./ydr
      dockerfile: Dockerfile 
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes:
      - ./ydr:/app
    networks:
      - my_network  


  backend:
    container_name: backend
    build:
      context: ./yourdir
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/yourdir_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - postgres
      - redis
    networks:
      - my_network 

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - my_network  


volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local   

networks:
  my_network:
    driver: bridge    
